name: Publish Documentation to GitHub Pages

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: write
  
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup Doxygen
      uses: ssciwr/doxygen-install@v1.0.0

    - name: Setup Python environment
      run: pip install Jinja2 Pygments

    - name: Build Documentation
      working-directory: ./build
      run: ./build_documentation.bat

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./documentation/html
